# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRedbubbleAuto():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()


  def get_current_browser():
      try:
          return webdriver.Chrome()
      except:
          pass
      
      try:
          return webdriver.Firefox()
      except:
          pass

      # Default browser is the chrome
      return webdriver.Chrome()

  
  # TODO file uploads on photoenlarger and redbubble,
  # and redbubble title, description, tags to fill out properly
  def test_redbubbleAuto(self):


    # 1. Navigating to chatGPT, to get the prompt to generate the pic with 
    # - the answer of it is not yet used, we could leave this part out for now  
    self.driver.get("https://chat.openai.com//")
    self.driver.find_element(By.ID, "prompt-textarea").click() # click into the prompt bar
    self.driver.find_element(By.ID, "prompt-textarea").send_keys("Generate a short prompt for an ai studio that generates pics that would be good so like describe the picture in the prompt that you would want the prompt is just the pic that you want to create so like \"modern good looking ball logo design\" or sg make it 20 words max\\n")
    self.driver.find_element(By.CSS_SELECTOR, ".md\\3A bottom-3").click() # send
    self.driver.find_element(By.CSS_SELECTOR, "rect:nth-child(2)").click() # copy the answer


    # 2. Generating the picture with this tool - Nightcafe AI
    # !! Make sure that the site is expanded to more than 960px - so e.g its full screen - otherwise it wont find all the elements
    self.driver.get("https://creator.nightcafe.studio/")
    self.driver.find_element(By.CSS_SELECTOR, ".css-skszrx .css-e3l1on").click() # clicking on create button
    # we could use chatGPT-s answer here
    self.driver.find_element(By.CSS_SELECTOR, ".css-1s3tkpv .mdi-icon").click() # random prompt picker
    self.driver.find_element(By.CSS_SELECTOR, ".css-fb7hnr > div:nth-child(1)").click() # submit request
    self.driver.find_element(By.CSS_SELECTOR, ".css-1vms9dz:nth-child(4) path").click() # download
    # Pause here to have time to download the file before navigating trough
    driver = self.get_current_browser()
    driver.implicitly_wait(0.5)


    # 3. Making the photo bigger so that it fits on items better
    self.driver.get("https://www.photoenlarger.com/")
    # "D\\Letöltések\\no5saNJ8rxAxr0DWs4Pn--1--9x5v2.jpg"
    self.driver.find_element(By.ID, "browseBtn").send_keys("yes.jpg") # selecting file to enlarge - doesnt work yet
    self.driver.find_element(By.ID, "resultScale").click()
    self.driver.find_element(By.ID, "resultScale").send_keys("400") # set desired scaling to 400% 
    self.driver.find_element(By.ID, "resultScale").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "enlargeBtn").click() # starting the process
    
    # handling the result
    self.driver.find_element(By.CSS_SELECTOR, "#lg4 .btn-group > .btn-group .fas").click() # starting download
    self.driver.find_element(By.CSS_SELECTOR, ".show > .dropdown-item:nth-child(1)").click() # selecting jpg


    # 4. Going to redbubble to upload the art
    self.driver.get("https://www.redbubble.com/")
    # clicking on profile icon on top right 
    self.driver.find_element(By.CSS_SELECTOR, ".node_modules--redbubble-design-system-react-Box-styles__display-inline-block--2MBBd > .node_modules--redbubble-design-system-react-Box-styles__box--2Ufmy > .node_modules--redbubble-design-system-react-Box-styles__box--2Ufmy > .node_modules--redbubble-design-system-react-Button-styles__button--2oYLO").click()
    self.driver.find_element(By.LINK_TEXT, "Sell Your Art").click() # clicking on "Sell your Art"
    self.driver.find_element(By.LINK_TEXT, "Add new work").click() # clicking on "Add new work"
    self.driver.find_element(By.ID, "select-image-single").send_keys("yes.jpg") # uploading the file - doessnt work yet

    # enabling all types of products for the design uploaded
    self.driver.find_element(By.CSS_SELECTOR, ".product-row:nth-child(2) > .all-disabled .enable-all").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-row:nth-child(11) > .slide:nth-child(2) .enable-all").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-row:nth-child(11) > .all-disabled .enable-all").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-row:nth-child(21) > .slide:nth-child(1) .enable-all").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-row:nth-child(21) > .all-disabled .enable-all").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-row:nth-child(31) > .all-disabled .enable-all").click()
    self.driver.find_element(By.CSS_SELECTOR, ".prerelease:nth-child(1) .enable-all").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-row:nth-child(50) > .slide:nth-child(2) .enable-all").click()
    self.driver.find_element(By.CSS_SELECTOR, ".all-disabled:nth-child(3) > .preview-info:nth-child(7) .enable-all").click()
    self.driver.find_element(By.CSS_SELECTOR, ".all-disabled > .preview-info:nth-child(7) .enable-all").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-row:nth-child(88) > .slide:nth-child(2) .enable-all").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-row:nth-child(88) > .all-disabled .enable-all").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-row:nth-child(139) > .all-disabled .enable-all").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-row:nth-child(129) > .slide:nth-child(1) .enable-all").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-row:nth-child(129) > .slide:nth-child(2) .enable-all").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-row:nth-child(129) > .all-disabled .enable-all").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-row:nth-child(118) > .slide:nth-child(1) .enable-all").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-row:nth-child(118) > .all-disabled .enable-all").click()
    self.driver.find_element(By.CSS_SELECTOR, ".all-disabled:nth-child(2) .enable-all").click()
    self.driver.find_element(By.CSS_SELECTOR, ".product-row:nth-child(108) > .slide:nth-child(1) .enable-all").click()
    self.driver.find_element(By.CSS_SELECTOR, ".all-disabled:nth-child(3) .enable-all").click()
    self.driver.find_element(By.CSS_SELECTOR, ".all-disabled .enable-all").click()

    # selecting the content type to be "Design and illustration" and "Digital Art" 
    self.driver.find_element(By.CSS_SELECTOR, ".add-work-details__media-type:nth-child(2) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".add-work-details__media-type:nth-child(5) > span").click()
    self.driver.find_element(By.ID, "work_safe_for_work_true").click() # its not mature content
    self.driver.find_element(By.ID, "rightsDeclaration").click() # accepting the Redbubble user aggreement
    
    # setting texts on top
    self.driver.find_element(By.ID, "work_title_en").click()
    self.driver.find_element(By.ID, "work_title_en").send_keys("example") # setting title 
    self.driver.find_element(By.ID, "work_tag_field_en").click()
    self.driver.find_element(By.ID, "work_tag_field_en").send_keys("example") # setting tags
    self.driver.find_element(By.ID, "work_description_en").click()
    self.driver.find_element(By.ID, "work_description_en").send_keys("example") # setting description
   
    self.driver.find_element(By.ID, "submit-work").click() # Submit the product
  
